feat: Verify migration with renaming
centrifuge/centrifuge-cli pull request #24
Opened 2022-03-28 14:16 UTC by NunoAlexandre

We add support to verify migrations that involve renaming of the migrated items, for example, `RadClaims.AccountBalances` -> `Claims.ClaimedAmounts`. For that, we now expect the config file with all the migrations to be performed to specify the `source` and the `destination` migratable item.

We also clean up the config so that there is no longer a need for both a general "ModuleConfig" and a "SequenceConfig"; the new `Migrations` type offers both the info about the items to migrate and implicitly the order in which the migrations must take place.

Finally, we improve some naming, structure, and grouping of code.

### New config example

```json
[
  {
    "source": {
      "pallet": "RadClaims",
      "item": "AccountBalances"
    },
    "destination": {
      "pallet": "Claims",
      "item": "ClaimedAmounts"
    }
  },
  {
    "source": {
      "pallet": "RadClaims",
      "item": "UploadAccount"
    },
    "destination": {
      "pallet": "Claims",
      "item": "UploadAccount"
    }
  }
]
```

2022-03-29 09:45 UTC, NunoAlexandre commented
@mustermeiszer one question here: the original config types supported specifying either a whole pallet or a pallet storage item. Do we have any use case for the first? If no, I can quickly clean up that same support in this new version and make both the code and the json simpler.

2022-03-29 11:33 UTC, mustermeiszer requested changes
Basically looks good. But the replacement of all logger calls to `console.log` will result in all log data being lost. I would revert this. 

And does the current logic mean one must name `source` and `destination` for all elements even if the naming does not change?

2022-03-29 11:33 UTC, mustermeiszer commented on packages/plugins/migration/src/commands/migration.ts
> +            console.log("Connecting to source chain: ", args["source-network"])
Why not using the logger?

2022-03-29 11:33 UTC, mustermeiszer commented on packages/plugins/migration/src/commands/migration.ts
> +                        console.error("❌ The following extrinsics failed:\n" + msg);
Every call to console will be lost. Those are not saved to file.

2022-03-29 11:38 UTC, mustermeiszer commented
> @mustermeiszer one question here: the original config types supported specifying either a whole pallet or a pallet storage item. Do we have any use case for the first? If no, I can quickly clean up that same support in this new version and make both the code and the json simpler.

No, we always use pallet+item combinations.

2022-03-29 12:25 UTC, NunoAlexandre commented on packages/plugins/migration/src/commands/migration.ts
> +                        console.error("❌ The following extrinsics failed:\n" + msg);
What do you mean with that, Frederik? Are the logs made through logger stored somewhere?

Between having them stored somewhere VS being actually able to read them on the console I prefer the latter. With logger all the logs are weirdly spaced and it's difficult to follow any message.

2022-03-29 12:45 UTC, NunoAlexandre commented on packages/plugins/migration/src/commands/migration.ts
> +                        console.error("❌ The following extrinsics failed:\n" + msg);
I didn't know that. However, I don't see the need to have it stored to a file. Do you? 

The migration summary is stored to a file and that is actually useful to store to pass to `--just-verify` if needed, the logs I don't see the need to store.

2022-03-29 12:47 UTC, NunoAlexandre commented on packages/plugins/migration/src/commands/migration.ts
> +            console.log("Connecting to source chain: ", args["source-network"])
With `this.logger.info` the logs are printed to my console all over the place. With `console.log` everything looks just fine.

Between having the logs stored somewhere VS being actually able to read them on the console, I prefer the latter. Wdyt? I'd be happy to use `this.logger` if we made it look sane but I also don't see the need to spend much time on that now.

2022-03-29 12:57 UTC, NunoAlexandre commented
> > @mustermeiszer one question here: the original config types supported specifying either a whole pallet or a pallet storage item. Do we have any use case for the first? If no, I can quickly clean up that same support in this new version and make both the code and the json simpler.
> 
> No, we always use pallet+item combinations.

Cool, simplified things in https://github.com/centrifuge/centrifuge-cli/pull/24/commits/f160a6de31248a3289e4bd9373ad46ec02efd00d 👍

2022-03-29 13:01 UTC, NunoAlexandre commented
> And does the current logic mean one must name `source` and `destination` for all elements even if the naming does not change?

Yes, the current `Migration` config type expect every migration spec to be explicitly name the source and the destination even if they follow the same naming. That allows for a single data structure for all cases, being explicit for all cases too, and it's really not a biggie to write this for a handful of migrations :) wdyt?

2022-03-29 13:26 UTC, mustermeiszer commented on packages/plugins/migration/src/commands/migration.ts
> +            console.log("Connecting to source chain: ", args["source-network"])
Have you tried expanding your terminal? The logger stores everything in a log file for each day. We introduced this one in order to have a source to look at in case something goes wrong.
I would really like to keep it. But not my call. Maybe sync with Miguel and decided then?

2022-03-29 13:35 UTC, NunoAlexandre commented on packages/plugins/migration/src/commands/migration.ts
> +            console.log("Connecting to source chain: ", args["source-network"])
Cool, will do! And sorry for having overlooked that.

2022-03-29 16:02 UTC, NunoAlexandre commented
λ node packages/cli/bin/run migration wss://fullnode-archive.centrifuge.io ws://127.0.0.1:11946  --config ../centrifuge-claims-test.json --creds ../creds.json

2022-03-29 15:59:03.367  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:25  Migration.run] Connecting to source chain:  wss://fullnode-archive.centrifuge.io
2022-03-29 17:59:03        API/INIT: RPC methods not decorated: anchor_getAnchorById
2022-03-29 17:59:03        METADATA: Unknown types found, no types for ProposalVotes
2022-03-29 15:59:03.953  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:35  Migration.run] Connecting to destination network:  ws://127.0.0.1:11946
2022-03-29 17:59:04        API/INIT: RPC methods not decorated: anchor_getAnchorById
2022-03-29 15:59:04.175  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:47  Migration.run] Starting migration from stand-alone chain block with hash 0x422c70498b97bc0a45e517618e32ee36c7d63fb5ea52c15bbd3a8075706c5dda
2022-03-29 15:59:04.177  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:62  Migration.run] Starting migration from parachain block with hash 0xee635568a38902f42784b1bff5fb3f3c3cc2c1068bf8b6c6de08fe9877ddc73b
Fetching storage for prefix: 0x1809d78346727a0ef58c0fa03bafa3231d885dcfb277f185f2d8e62a5f290c85
Fetched keys: 75
Fetched storage values: 75/75
Fetching storage for prefix: 0x85051ca90552b2ab118f60536b77c036cf2cea66e15b13680a7bd4ce2022a181
Fetched keys: 370
Fetched storage values: 370/370
No checks performed, due to unavailability of `dry_run()` on chain.
Sending with nonce 502, running 1 : migrate_proxy_proxies
Sending with nonce 503, running 2 : migrate_proxy_proxies
Sending with nonce 504, running 3 : migrate_proxy_proxies
Sending with nonce 505, running 4 : migrate_proxy_proxies
Waiting in perBlock... 5
Sending with nonce 506, running 5 : migrate_proxy_proxies
Sending with nonce 507, running 6 : migrate_proxy_proxies
Sending with nonce 508, running 7 : migrate_proxy_proxies
Sending with nonce 509, running 8 : migrate_proxy_proxies
Sending with nonce 510, running 9 : migrate_proxy_proxies
Waiting in perBlock... 10
Sending with nonce 511, running 10 : migrate_proxy_proxies
Sending with nonce 512, running 11 : migrate_proxy_proxies
No checks performed, due to unavailability of `dry_run()` on chain.
Sending with nonce 513, running 12 : set_storage
Sending with nonce 514, running 13 : set_storage
Sending with nonce 515, running 14 : set_storage
Sending with nonce 516, running 15 : set_storage
Sending with nonce 502 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 502
Sending with nonce 503 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 503
Sending with nonce 504 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 504
Sending with nonce 505 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 505
Waiting in perBlock... 5
Sending with nonce 517, running 12 : set_storage
Sending with nonce 518, running 13 : set_storage
Sending with nonce 519, running 14 : set_storage
Sending with nonce 520, running 15 : set_storage
Sending with nonce 521, running 16 : set_storage
Waiting in perBlock... 10
Sending with nonce 522, running 17 : set_storage
Sending with nonce 523, running 18 : set_storage
Sending with nonce 524, running 19 : set_storage
Sending with nonce 525, running 20 : set_storage
Sending with nonce 526, running 21 : set_storage
Sending with nonce 506 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 506
Sending with nonce 507 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 507
Sending with nonce 508 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 508
Sending with nonce 509 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 509
Sending with nonce 510 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 510
Sending with nonce 511 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 511
Sending with nonce 512 is in Block/Finalized : migrate_proxy_proxies
Sudo ok: 512
Sending with nonce 513 is in Block/Finalized : set_storage
Sudo ok: 513
Sending with nonce 514 is in Block/Finalized : set_storage
Sudo ok: 514
Sending with nonce 515 is in Block/Finalized : set_storage
Sudo ok: 515
Sending with nonce 516 is in Block/Finalized : set_storage
Sudo ok: 516
Waiting in perBlock... 15
Sending with nonce 527, running 11 : set_storage
Sending with nonce 528, running 12 : set_storage
Sending with nonce 529, running 13 : set_storage
Sending with nonce 530, running 14 : set_storage
Sending with nonce 531, running 15 : set_storage
Sending with nonce 517 is in Block/Finalized : set_storageRunning: 15
Sudo ok: 517
Sending with nonce 518 is in Block/Finalized : set_storage
Sudo ok: 518
Sending with nonce 519 is in Block/Finalized : set_storage
Sudo ok: 519
Sending with nonce 520 is in Block/Finalized : set_storage
Sudo ok: 520
Sending with nonce 521 is in Block/Finalized : set_storage
Sudo ok: 521
Sending with nonce 522 is in Block/Finalized : set_storage
Sudo ok: 522
Sending with nonce 523 is in Block/Finalized : set_storage
Sudo ok: 523
Sending with nonce 524 is in Block/Finalized : set_storage
Sudo ok: 524
Sending with nonce 525 is in Block/Finalized : set_storage
Sudo ok: 525
Sending with nonce 526 is in Block/Finalized : set_storage
Sudo ok: 526
Sending with nonce 527 is in Block/Finalized : set_storageRunning: 5
Sudo ok: 527
Sending with nonce 528 is in Block/Finalized : set_storage
Sudo ok: 528
Sending with nonce 529 is in Block/Finalized : set_storage
Sudo ok: 529
Sending with nonce 530 is in Block/Finalized : set_storage
Sudo ok: 530
Sending with nonce 531 is in Block/Finalized : set_storage
Sudo ok: 531
2022-03-29 16:00:00.883  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:93  Migration.run] ✅ Migration was successful.
2022-03-29 16:00:00.893  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:111  Migration.run] Ending migration on destination chain at block hash0x11fafb55bfa47fdf03c5d5e376316f8070dff2417192634236e0e32e67b01eb2
2022-03-29 16:00:00.971  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:192  Migration.writeSummary] The following migration summary will be written to disk now:
   {
  "fromStartedAt": 10322251,
  "fromFetchedAt": 10322251,
  "toStartedAt": 2270,
  "toEndAt": 2275
}
2022-03-29 16:00:00.974  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:195  Migration.writeSummary] ✔️ Summary written to  /Users/n/.cfgCli/Migration/Summaries/migration-1648569600971.json
2022-03-29 16:00:00.974  INFO  [Migration packages/plugins/migration/src/commands/migration.ts:167  Migration.run] 👋 Done, bye now.
```

2022-03-30 07:03 UTC, NunoAlexandre commented
@mustermeiszer @mikiquantum I figured what's going on. What seems to be indentation is actually text with the same color as the background 😆

2022-03-30 07:34 UTC, mustermeiszer approved these changes
LGTM!

2022-03-30 07:49 UTC, merged